//
// Family.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Family: Codable {


    public var _id: String?

    public var name: String

    public var qrCode: String?

    public var users: [User]?

    public var createdBy: User?
    public init(_id: String?, name: String, qrCode: String?, users: [User]?, createdBy: User?) { 
        self._id = _id
        self.name = name
        self.qrCode = qrCode
        self.users = users
        self.createdBy = createdBy
    }

}
