//
// ListModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ListModel: Codable {


    public var _id: String?

    public var title: String

    public var color: String

    public var createdDate: String?

    public var createdBy: User?

    public var items: [ListItem]?

    public var family: Family?
    public init(_id: String?, title: String, color: String, createdDate: String?, createdBy: User?, items: [ListItem]?, family: Family?) { 
        self._id = _id
        self.title = title
        self.color = color
        self.createdDate = createdDate
        self.createdBy = createdBy
        self.items = items
        self.family = family
    }

}
