//
// ListCreateUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ListCreateUpdate: Codable {


    public var title: String
    public init(title: String) { 
        self.title = title
    }

}
