//
// ListItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ListItem: Codable {


    public var _id: String?

    public var name: String

    public var parentId: String?

    public var checked: Bool?

    public var checkedAt: String?
    public init(_id: String?, name: String, parentId: String?, checked: Bool?, checkedAt: String?) { 
        self._id = _id
        self.name = name
        self.parentId = parentId
        self.checked = checked
        self.checkedAt = checkedAt
    }

}
