//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct User: Codable {


    public var _id: String?

    public var initials: String?

    public var firstName: String

    public var lastName: String

    public var password: String

    public var email: String

    public var token: String?
    public init(_id: String?, initials: String?, firstName: String, lastName: String, password: String, email: String, token: String?) { 
        self._id = _id
        self.initials = initials
        self.firstName = firstName
        self.lastName = lastName
        self.password = password
        self.email = email
        self.token = token
    }

}
