//
// UserUpdateModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct UserUpdateModel: Codable {


    public var firstName: String

    public var lastName: String

    public var password: String?

    public var email: String
    public init(firstName: String, lastName: String, password: String?, email: String) { 
        self.firstName = firstName
        self.lastName = lastName
        self.password = password
        self.email = email
    }

}
